name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - pandas
  - bqplot
  - geopandas
  - contextily
  - scipy
  - palettable
  - h5py
  - descartes
  - ipyvolume
  - ffmpeg
